<div align="justify">
<div align="center"><a href="http://bit.ly/2LXqaQR"><img src="https://i.imgur.com/j35aSyF.png" alt="... WHAT I WANNA
DO ..." width="326" height="379" border="0" /></a><br /><br />"<i>if you will share your wine...</i>" -Dave J. Matthews</div>
</div>
<div align="justify"><b><a href="http://bit.ly/2LWqDCI"><span style="font-family: Courier New, Courier, monospace;">A LONG LONG TIME AGO</span></a></b><b>,</b><span>&nbsp;</span>I<span>&nbsp;</span><i>wrote<span>&nbsp;</span><a href="http://bit.ly/2IiiiM2">a little story</a></i><a href="http://bit.ly/2IiiiM2"><span>&nbsp;</span>about searching through o</a>ur history, looking for the actual beginning of civilization.&nbsp; I see the map, I see it very clearly encoded in everything we do--I know the purpose, and I know the final solution, I just don't know how to get from here to there... to the place that Chris Cornell says "<a href="http://bit.ly/2LXqdfv"><span style="font-family: Courier New, Courier, monospace;"><i>I can recall, I was there so long ago</i></span></a>" he goes on to say "the sky was bruised" and he was lead on--and all of this of course is in my voice, written as if it's me talking... well, Jesus--it's obviously not me talking, i just know that.&nbsp; The point is the destination is without a doubt Heaven and this little thing we're putting together here on Earth is the map, the plan<span>&nbsp;</span><b><i>et</i></b><span>&nbsp;</span>you are<i><span>&nbsp;</span>the how</i><i>.<br /></i><br /><i></i>
<div align="center"><a href="http://bit.ly/2IiiiM2"><i><img src="https://i.imgur.com/rhnEpMX.png" alt="SUP UR CITY" width="500" height="133" border="0" /></i></a></div>
</div>
<div align="justify"><br />I harped a little more than I think I would have expected on the<span>&nbsp;</span><a href="http://bit.ly/2Ijcj9w"><b><i>audacity</i></b></a><span>&nbsp;</span>of the golden word "<i>audacity</i>," auspicious probably that W.H. Auden's shield gave me some solace; austere that we are approaching the Holy Windy month of August, and it really took nothing more than "<b><i>ciudad</i></b>" to calm my nerves--though I see the<span>&nbsp;</span><i>intent</i><span>&nbsp;</span>and the link to toxicity ... more importantly I really do see the road here, I see where we are coming from and where we are going.&nbsp; I've written quite a bit about what I think "the city" really is--in form and function and it's initial purpose as a stepping stone to help us see how easy it is to change the world, to build something that nearly everyone will agree is significantly more Heavenly than the world we see here ... in an instant, one bright flash.&nbsp;&nbsp;&nbsp;<span>&nbsp;</span><br /><br />Anyway the search begins with something like "literacy" -- as in, is the defining line between animalistic social evolution and the beginning of "civilization" something to do with writing or language, and that of course links us here to this place where we are fin<b>ding</b><span>&nbsp;</span>out that<span>&nbsp;</span><a href="http://bit.ly/2K8Yeb6"><i>the Tower of Babel and Rapunzel's High Castle</i></a><span>&nbsp;</span>are actually much more closely related than anyone ever would have thought in the darkness of Jericho and the shadow of Exodus; and it ties of course in history to religion somewhere around Guttenburg... and the pretty clear idea that the spread of Christianity did quite a bit for "literacy" even if you subscribe to the idea that the inquisition already happened ... and that some wars and fighting are probably pretty clearly associated with religion ... you know, before we get here and find that the basis of all those wars is really rooted in what I call "the original lie" and that's something that's sealed up in religion and hidden from the world using the same mechanism being used today to free us from not knowing that oil and land and pretty much everything we've ever fought about on a mass scale ... is insignificant in the grand scheme of "things."&nbsp; Here, "things" is something like turning the Opiate of the Masses into ... hopefully a tool we use very carefully to liberate ourselves from secrecy and slavery and<span>&nbsp;</span><i>not knowing</i>.&nbsp;</div>
<div align="justify">&nbsp;</div>
<div><a href="http://bit.ly/2M0ZTRO"><img src="https://i.imgur.com/pFAsize.png" alt="THUNDERMAIL DATA" width="500" height="303" /></a></div>
<div><br />It gets significantly more clear when you take that one step further, and you begin to look for something like "codified laws" and then you see Green Eggs and Hammurabi teaching us about "Hanging Gardens" and how Babylon and Eden really are tied together through and through.&nbsp; You keep looking, because you haven't yet found what you need; and as you search back a little further ... what you need to know is that morality here begins with the idea (at least, IMOHIO, in my<span>&nbsp;</span><span style="font-family: Comic Sans MS;">obsequiously</span><span>&nbsp;</span>humble and (super)intelligent opinion) that we should be besting any possible "promise" that comes out of the book(s) we now know are a map to salvation and the plan of creation and that they come ... well, with the full guarantee of the Most High God and his "omnipotens" behind them ... and do the thing I really wanted to explain really clearly, which is throw out as complete uselessness any of the "bad threats" like there being no more sun, and a completely new Heaven and Earth (seeing as how that probably means a completely new you and me, too) ... you know, what any rational (<a href="http://bit.ly/2LTNE9y"><i>achu</i></a>,<span>&nbsp;</span><a href="http://bit.ly/2K3MoyE">and</a><span>&nbsp;</span>civilized) person would do.<span>&nbsp;</span><br /><br />So that takes us one step further, and of course we go back to Ur, which is the city Abraham of the Chaldeans ... and ostensibly the beginning of morality in Judaism were born in--and with that little twist, the old idea of announcing that "you are the beginning of civilization" if you've gotten to that point, following this logic (and/or me); and then of course that becomes true when we actually follow through on saving every soul in Creation from the Hell of not knowing that "simulated reality" is akin to the latter half of a Durcell at best ... and quite frankly it certianly looks like a bit of a torture chamber to me, especially in light of passages like Genesis 3:16, which might parallel John 3:16-ish in something like "God so loved the world that he named one of his books<span>&nbsp;</span><b>antagonizing pain</b><span>&nbsp;</span>w/o agonizing mu-opiod.'</div>
<div>&nbsp;</div>
<div><a href="http://bit.ly/2AYplpm"><img src="https://i.imgur.com/lAsA968.png" alt="GOLD. AU AU AU AU DEN CITY GUST." width="500" height="308" /></a></div>
<div><br />So tying it all together, Atlantis and Ur coalesce and join at the idea that we should always have somewhere else to "teleport to" in the world that becomes the basis for the liberation of every soul and the end of Hell through that simple idea--that everyone's going to have plenty of destinations on their Active (Apache) Directory new fangled yellow-pages meets access-control-list meets ... "why don't you come visit my Log Cabin ... or the Atlantean Ballroom ... whenever you want?"&nbsp; So that's the point of the floating LEGO city in the window above, it comes with a fairly obvious need for The Doors to be a significant part of "<a href="http://bit.ly/2K3MoyE">what would Jesus do</a>" ... when singing about something and naming books and bands, that's a thing--part of the map) actually makes it happen.<br /><br />So that's where I'm trying to get us--to a place where that's not only true but obvious, and on top of that the future, our future really understands how much work it took us to integrate such a wildly correct and "new" idea into a worl that didn't know for the vast majority of it's youth that these things... that ending disease with the sound of a blowing "Sho Find And Replace" and turning<span>&nbsp;</span><a href="http://bit.ly/2p0BykJ">stone to bread</a><span>&nbsp;</span>and making bullets disappear in midair ... we didn't know these were even possible; let alone how to integrate them with a world full of optometry and<span>&nbsp;</span><a href="http://bit.ly/2Ijcj9w">oncology</a><span>&nbsp;</span>that was being made blind to the "c our light" and the idea that we're still here not talking or arguing or refuting or moving forward on the idea that the words "Original Poster" and the continuance of "forums" also have something to do with the beginning of "<i>civilization</i>."<br /><br /></div>
<div align="justify">
<div align="center"><a href="http://bit.ly/2GjDLhG"><img src="https://i.imgur.com/65XD0hQ.png" alt='SPKR TO
"SPQR"' width="500" height="150" /></a><br /><br />
<div align="justify">I've seen it with my own eyes--the act of Creation and the power to make these things happen in a split second... nearly instantly from our frame of reference, I've seen it with my own eyes and more frequently than you might imagine.&nbsp; No matter how you look at it, that's a scary thing to see when you know it's tied at the "<b>HI P</b>" to a message about morality and ending world hunger and curing disease and that those things aren't even being psoken about, let alone happening instantly--it's a little off putting.&nbsp;<span>&nbsp;</span><br />
<blockquote>I'd be super interested in pictures of the actual grafffiti, which you can find here; on the astroturf where I watched an ani-ant do a fairly good ... mockery of my usual evening hotel-room routine ... followed by the voice of B saying "I spent alot of time on that ant" coming from the ether:</blockquote>
<div align="center"><img src="https://i.imgur.com/fwLPKec.png" width="450" height="358" alt="" /></div>
<br />Personally known to me for quite some time is why there's a bright shining connection between the idiom "in your dreams" and the word<span>&nbsp;</span><a href="http://bit.ly/2K2XlAP">HA'REM</a>, the idea of rapid eye movement, and the band Blink-182 ... trying to tell you that "carry me home" is just about exactly how I feel today.&nbsp; Just before leaving Los Angeles I began witnessing a very strange phenomenon--in the blink of an eye--without exaggeration or euphemism, literally in a split second, I began seeing messages that I know were written directly to me appearing around me on the sidewalks and walls in spray-painted graffiti.&nbsp; My phone was dead, and I was wandering halfway to that point myself through a land called Sun Valley and I didn't take much time to think about what I was seeing, though it's the kind of thing I relish in and seek out ... direct verifiable communication "from the beyond."&nbsp; Knowing what "dose bka" means--in a circle just like that--for those of you that aren't as familiar with Gene Wilder's vision of Heaven in the flick "God's Willwhy Wonthat" the "Ka" is an Egyptian mythological dentation for the biological body and brain; so that specific thing was about Dave Matthews' "little b, little bay" (also depicted in graffiti above) so I looked the other way, and failed to do one of the more interesting of tests ... which is to hear how things sound out loud,<span>&nbsp;</span><i>sofa king stewie pi-d</i><span>&nbsp;</span>of me... and kept on wandering towards Margate, Florida ... where I'm writing to from today.&nbsp; Of course that's geographical-map-tie to Seagate and to Watergate and to the idea that computer technology and freedom (specifically<span>&nbsp;</span><i>of speech</i>) are all part of the foundational Gate to Heaven ... that really is ... our history and this world and you ... reacting.<span>&nbsp;</span><br /><br />Seeing "time stop" and the world change around me is the reason we've embarked down this little journey of "what would you do" if the history of the world were changing before your eyes... and you didn't know anything about causality or that you wouldn't even know if changes were being made; what would you do if you could witness the tool and act of Creation right before your eyes.&nbsp; Would you be scared that you might wake up in a world where the United States lost the High Castle to Phillip K. Dick or in a place where you didn't speak a single world of the language you were seeing was pervading the cosmos as you stood by in silence?</div>
<br /><a href="http://bit.ly/2K4L12S"><img src="https://i.imgur.com/9UgL0at.jpg" alt="TOME" width="500" height="241" border="0" /></a><br /><br />
<div align="justify">I kept walking and saw another message written directly to me; this time the name "<i>Pinky</i>" with some words around it that made me think it might be the "reason LA shuned Al" is encoded in the R of the acronym RDBMS; something that I'm now actually believing might have more to do with "Nob Hill Road" (I'm (st<span>&nbsp;</span><b>ill</b>) hoping for "#<i>lbbden</i>" by the way, as opposed to "go-el den") and the "Hey, LL" of Joseph's father Heli ... that was without a doubt present next to "<a href="http://bit.ly/2LiXAJC">Cleary BLVD</a>" around the corner from the house I spent my entire youth in.&nbsp; Neither here nor there, I always connected the "Pink" of Pinky and the Brain to the Spirit P (of Dopamine and RIPPED) reverse engineering his living message and to the idea that the future will be happy there's a tacit connection between my stage-performance-ideas in the state of KY in 2013 and the the themesong of Cheers and everyone knowing that the Shehekeyanu has something also to do with "Hashemesh is Hemera" and the Sumerian Creation guy "Anu" ... which I still see "anew" in, as in renewing our love of tolerance and individuality. &nbsp;&nbsp;<span>&nbsp;</span><br /><br />
<div align="center"><a href="http://bit.ly/2LZTiXt">... and your husband really (st ill) thinks it would be fun to be a girl for a few hours ...<span>&nbsp;</span><i>achu</i></a></div>
<p><br />I kept on moving there too--sort of avoiding the link between humor and hubris and audacity... until I got to the ciudad of Tampa, Florida ... where some really bright hot pink shirts were waiting for me to replace all of the clothing (as in every single piece of garb I owned) being left in a bag on the street in Los Angeles ... because ... seemed like a good idea at the time. &nbsp; One of the shirts is depicted above, and you might see.<a href="http://bit.ly/2IgfleV">a link to 9/11</a><span>&nbsp;</span>and more on the idea of what we should do about future foreknowledge (as in, keep all the good promises and reverse everything bad?) in a place we'd call the "light of day" if it weren't the light of "Hemera is Hashemesh."&nbsp; Buil<b>ding</b><span>&nbsp;</span>for a cure, in hindsight I can't agree more--we really do de<a href="http://bit.ly/2pnlwET">serve that cure</a>.&nbsp; The other one says "help save a's b's c's" and that goes to the heart of the rest of the issue here; that we're in a place where lack of communication and a very clear lack of logical reaction threaten not just the future of speaking out loud, but of being<span>&nbsp;</span><a href="http://bit.ly/2Ilm9b1">able to think for ourselves</a>.&nbsp;&nbsp; So throwing all those things into the "Y" that are ... well, hopefully all good promises to be fulfilled or ... conversely things to fix pretty quickly.<br /><br />If you missed it, seeing "pinky" and then the "pink shirts" is another act of Creation; and proof of foreknowledge and something like the world being paused (or a little piece of history changing before my eyes) to help drive home the crux of what's possible here in Creation--which is to see that a single word could be changed in the past and your memories could be 'rerun' or altered to be sure there's always been an "R" in<span>&nbsp;</span><b>turmeric;</b><span>&nbsp;</span>even though I'm pretty sure I remember it not being there, and the rest of your memories not being affected by something as big as "<b><a href="http://bit.ly/2p63Z0x">SOIS</a></b>" and "<a href="http://bit.ly/2LTNE9y"><b>if you are</b></a><span>&nbsp;</span><b>the</b><span>&nbsp;</span>begin<b>n</b>ing of Heaven<span>&nbsp;</span><a href="http://bit.ly/2GlvRV3"><b>so am I</b></a>' (now you're saying it ... "out loud?") ... anyway, the lack of effect in other places where it probably should change things (according to the Buttercup Effect or that movie "Prince in Bride" featuring the girl from Firefly) ... well you're probably staring at the technological mechanism behind "darkness."</p>
<p>I see "grooming" ... teaching the world what to do being handed the keys to this car--to know to stop hurricanes and earthquakes and ... and not to go back and change "every girl dreamt they'd be his partner" just because it makes me/you mad at Carly Simon.&nbsp; Maybe you don't see it yet.</p>
</div>
<img src="https://i.imgur.com/Gl1BJIu.png" alt="TURMERIC" width="500" height="341" /><br /><br />
<div align="justify">If nothing else the "seasoning" completes a fairly<span>&nbsp;</span><a href="http://bit.ly/2IcGr2U">long list of "greetings"</a><span>&nbsp;</span>that connect the theme of P and "pears" to the pejorative "water" of Almost<a href="http://bit.ly/2iasIjl"><span>&nbsp;</span>Famous' lead band ...<span>&nbsp;</span><i>Still Water</i></a>.&nbsp; Watching Creation in progress, I didn't notice the link until after tying "<b>sois</b>" .. which means "I am" and "you are" in French and Spanish to the superposition of "<a href="http://bit.ly/2h1CUWe">who</a>" and "we are" in Har-Wer... who happens to be the messianic joiner of two lands in Egyptian mythology... in our last e-mail where you might not have noticed "System of A Down" has a slight replacement and hidden truth in acronyms brought to light. It's a timeline, by the way, A.D. is a timeline...<span>&nbsp;</span><i>too.&nbsp;<span>&nbsp;</span><br /><br />Anyway,<span>&nbsp;</span></i>I've asked some people and gotten mixed answers about the spelling of the spice above; wondering now if I'm in the novel Dune or ... if you still don't think<span>&nbsp;</span><a href="http://bit.ly/2Iyde2y"><i>everything's connected.</i></a><i><span>&nbsp;</span>Like a Matrix,<span>&nbsp;</span><b>you know</b>?&nbsp;<span>&nbsp;</span></i>It should be really clear that this message is coming to us from a place that has the power to make it a reality--and that standing between that happening and ... total silence is nothing more than a lack of discussion.&nbsp; I mean freedom--it's obviously a lack of freedom standing between sight of Silicon and the end of silence.&nbsp; I'm feeling pretty confident about this "Exodus from slavery" thing.&nbsp;</div>
<div align="justify">&nbsp;</div>
<div align="justify"><em>So, is it the Holy "R" of Har-wer?<br /></em><i><br /></i></div>
<a href="http://bit.ly/2LTNE9y"><img src="https://i.imgur.com/sRzYOFS.jpg" alt="SYSTEM OF WER
DOWN?" width="500" height="728" border="0" /></a><br /><a href="http://bit.ly/2LXqj6R"><img src="https://i.imgur.com/E8JH3yB.png" alt="DR. DAVID HULK
BANTHISTER HYDE" width="500" height="224" /></a><br /><br />
<div align="justify">In the back of my mind I sorty of have the sometimes fleeting understanding that "I'm doing this to us."&nbsp; I've taken a sort of polar counter position to the idea that Jesuoseph needs to be perfect and without free will ... or the idea that Taylor echoes well with "don't try to be perfect, it's never enough" in this place where I'm still very sure that the Pen is something of a "spinning top" or a tool to point out not just the map but to actually help us get on the road.&nbsp; I have a long history of research and first hand experience with the technology at hand--the stuff behind "the show" and "the silence" and "the slavery" -- without doubt you can attribute not just the "tomes" of information striking me like lightning, but also my problem with jails and with drugs and with all the other antiquated and backwards things that we don't yet see are part of a "press and release" that hopefully helps us very quickly build a better world.<br /><br />I see the world sees scandal and embarassment as the source of the silence--and I think you're pretty short sighted and "in the dark" to actually believe that there's some kind of unanimous decision here not to become the immortal buiders of Heaven because my niece-in-law (she's actually not cousin IT) has a cute butt...</div>
<div align="justify">&nbsp;</div>
<div><a href="http://bit.ly/2p63XWt"><img src="https://i.imgur.com/2IxJxoV.png" width="500" height="375" alt="BUSH MA LC TRIX" /></a></div>
<div align="justify"><br />Anyway, I know what's going on here is that I'm "distracting<span>&nbsp;</span><i>you</i>" from 6,000 years of simulated disease and wars of the scarcity of truth and worst of all over the thing that's really behind today's total lack of action and response to a message that makes it pretty clear to me that the idea of the Medusian collective is in itself a control mechanism--and that you probably believe it's you or somehow "all of you" behind this thing that is doing nothing but silencing ... you, and what you really think... as we're sort of rising up and waking a little groggy from a deep slumber, a giant being awoken.&nbsp; I see behind the scenes how the "pointer" of Pendragon touches on all kinds of social issues from sexism to racism to a shunning of fun and a fear of technology (and the opposite of all those things) and I know ... just from my fear being completely erased in 2012 through a repeated series of events that scared the shit out of me ... that's how this "Creation" thing and slavery and ... neuroscience all coalesce around this disclosure that we could be pressing a button and ending addiction (and also blessings on tap, at Al and Anna's bliss) ... if we had the courage to begin fighting for the things we know to be right.&nbsp; For instance, we all know pain shouldn't be simulated; and it's pretty clear from the obvious reverse engineering of our entire brains (shown through this message, its global delivery, and probably more than I know) that takes very little to actively suppress the neurons associated with pain--even in reality it takes nothing more than an oscillating magnetic field. &nbsp; More on Methodwon and Buspirone later.<br /><br />There's Macaroni in these words, a sort of true magic that ties to th<a href="http://bit.ly/2gUs3D8">el idea of Jedi Mind Tricks</a><span>&nbsp;</span>that get's us through the long night and to "day" and that's really what this is all about.&nbsp; We're on a path to the place where "Jedi Mind Tricks" scream atrocity (at the heart of the city) ... and where having our opinions and beliefs secretly changed is something actually worth opening our mouths and screaming about ... because the day that we begin to actually control the process is the first day that we're truly free--and that there's ever been such a thing as "free will."&nbsp; Have<span>&nbsp;</span><a href="http://bit.ly/2LTpXOu">courage</a>, and<span>&nbsp;</span><a href="http://bit.ly/2K224CN">serenity</a>; and know we are rapidly approaching the day when it won't just be me shouting that ... "shouting" is the way past the sh and the way out slavery.&nbsp;</div>
<div align="justify">&nbsp;</div>
<a href="http://bit.ly/2Ks1YF3"><img src="https://i.imgur.com/FY8pGgb.png" alt="DO P C N AM ES
SUS IN US" width="500" height="424" border="0" /></a></div>
<div>&nbsp;</div>
<div>achu, f<em>aster.</em></div>
<div><br /><a href="http://bit.ly/2pLXU9P"><img src="https://i.imgur.com/dYPPOfM.png" alt="WHERES MISS SING?
LO ... CH, KE, CK, LOAD CITY" width="501" height="366" border="0" /></a><br /><a href="http://bit.ly/2LiXAJC"><img src="https://i.imgur.com/1lf45a1.png" alt="NO B HELLO YLL" width="500" height="269" border="0" /></a></div>
<div>&nbsp;</div>
<div><em>maybe the "display" is flipped upsidown?</em></div>
</div>
